export type WellbeingArticle = {
  slug: string;
  title: string;
  description: string;
  paragraphs: string[];
  questions: string[];
  source: string;
};
export type WellbeingTopic = {
  group?: "conoscere" | "prevenire";
  slug: string;
  title: string;
  description: string;
  image: string;
  articles: WellbeingArticle[];
};
const nci = "https://www.cancer.gov";
export const wellbeingTopics: WellbeingTopic[] = [
  {
    group: "conoscere", slug: "conoscere-i-tumori", title: "Conoscere i tumori",
    description: "Le parole e le domande da cui partire per comprendere la malattia, senza usare le informazioni per diagnosticarsi da soli.", image: "/images/editorial/supporto.svg",
    articles: [
      { slug: "cosa-sono", title: "Cosa sono i tumori", description: "Una parola che comprende malattie diverse.", paragraphs: ["Il cancro comprende malattie in cui alcune cellule crescono in modo incontrollato e possono invadere altri tessuti. Non tutti i tumori sono uguali: origine e caratteristiche biologiche contano nel percorso diagnostico e terapeutico.", "Un tumore benigno non invade i tessuti vicini e non produce metastasi, ma può comunque richiedere controlli o trattamento. La distinzione non si può stabilire dal solo aspetto di un sintomo: serve una valutazione medica."], questions: ["Qual è il nome preciso della diagnosi?", "Quali esami ne chiariscono le caratteristiche?"], source: `${nci}/about-cancer/understanding/what-is-cancer` },
      { slug: "glossario", title: "Le parole della diagnosi", description: "Un primo glossario per orientarsi nei colloqui.", paragraphs: ["Biopsia: prelievo di cellule o tessuto da esaminare. Metastasi: diffusione del cancro dalla sede di origine a un’altra parte del corpo.", "Benigno e maligno descrivono caratteristiche diverse del tumore. Una parola letta su un referto non basta per interpretare tutta la situazione: chiedi al medico di spiegare il documento nel suo insieme."], questions: ["Può spiegarmi questi termini nel contesto del mio referto?", "Quali informazioni sono ancora da chiarire?"], source: `${nci}/about-cancer/understanding/what-is-cancer` },
      { slug: "ricerca-e-patologie", title: "Le patologie al centro della ricerca A-ROSE", description: "Collegare informazione e domande scientifiche, senza confondere studi e cure disponibili.", paragraphs: ["Nei progetti presenti sul sito A-ROSE compaiono mammella, colon, endometrio, polmone, melanoma e mesotelioma. I progetti affrontano domande specifiche: non rappresentano una guida terapeutica per ogni persona con queste diagnosi.", "Per leggere uno studio distingui l’obiettivo dai risultati, e i risultati sperimentali dalle applicazioni cliniche. La descrizione di un bersaglio da studiare non dimostra che esista già una terapia disponibile."], questions: ["Lo studio è sperimentale o riguarda un trattamento già disponibile?", "Quali risultati sono stati pubblicati?"], source: "/la-ricerca/progetti" },
    ],
  },
  {
    group: "prevenire", slug: "stili-di-vita", title: "Stili di vita e prevenzione",
    description: "Scelte quotidiane e accesso alla prevenzione: ridurre il rischio non significa azzerarlo, e ammalarsi non è una colpa.", image: "/images/editorial/movimento.svg",
    articles: [
      { slug: "alimentazione", title: "Alimentazione: conta l’insieme", description: "Abitudini sostenibili, non cibi miracolosi.", paragraphs: ["Le raccomandazioni di prevenzione danno spazio a cereali integrali, legumi, frutta e verdura e invitano a limitare carni rosse e lavorate. Non esiste un alimento che da solo protegga dal cancro.", "Queste indicazioni di popolazione non sostituiscono un piano personalizzato e non vanno trasferite automaticamente all’alimentazione durante le cure."], questions: ["Come posso adattare le indicazioni alle mie esigenze?"], source: "https://cancer-code-europe.iarc.who.int/" },
      { slug: "fumo-e-alcol", title: "Fumo e alcol: chiedere supporto per cambiare", description: "Informazioni e aiuto pratico, senza giudizi.", paragraphs: ["Evitare il tabacco e il fumo passivo fa parte della prevenzione. Per l’alcol, non bere è la scelta migliore per ridurre il rischio oncologico.", "Se cambiare abitudine è difficile, chiedi al medico quali servizi possono aiutarti. Il supporto professionale è una risorsa, non il segno di un fallimento."], questions: ["Quali servizi del territorio possono aiutarmi?"], source: "https://cancer-code-europe.iarc.who.int/" },
      { slug: "movimento-e-sole", title: "Movimento e protezione dal sole", description: "Due aspetti della vita quotidiana da non trascurare.", paragraphs: ["Muoversi regolarmente e ridurre il tempo trascorso seduti sono indicazioni di prevenzione. Scegli attività compatibili con le tue condizioni.", "Evita l’esposizione eccessiva ai raggi UV e le lampade abbronzanti. Ombra, indumenti e protezione solare aiutano a proteggere la pelle: non usare la crema per prolungare l’esposizione."], questions: ["Ci sono precauzioni specifiche per le mie condizioni o i miei farmaci?"], source: "https://cancer-code-europe.iarc.who.int/" },
    ],
  },
  {
    slug: "alimentazione-durante-le-cure", title: "Alimentazione durante le cure",
    description: "Quando mangiare diventa diverso dal solito, informazioni chiare e un supporto personalizzato aiutano a orientarsi. Non una dieta per tutti, ma domande e strumenti per parlarne con chi ti cura.",
    image: "/images/editorial/alimentazione.svg",
    articles: [
      { slug: "prepararsi-alle-cure", title: "Prepararsi alle cure: il supporto nutrizionale", description: "Da dove iniziare e quali informazioni condividere con il team.", paragraphs: ["Le esigenze alimentari durante i trattamenti possono essere diverse dalle raccomandazioni generali per la prevenzione. Una valutazione nutrizionale considera condizioni individuali, terapia e difficoltà nel mangiare.", "Prima della visita puoi annotare le tue abitudini, eventuali variazioni di peso e ciò che rende difficili i pasti. Porta anche l’elenco di integratori e prodotti che assumi: aiuta a costruire un quadro completo."], questions: ["È indicata una valutazione nutrizionale?", "A quale professionista posso rivolgermi nel mio percorso di cura?"], source: `${nci}/about-cancer/treatment/side-effects/appetite-loss/nutrition-hp-pdq` },
      { slug: "difficolta-ai-pasti", title: "Quando mangiare diventa difficile", description: "Appetito, gusto e disturbi da raccontare al team curante.", paragraphs: ["Malattia e terapie possono modificare appetito, gusto e olfatto. Anche disturbi della bocca o difficoltà a deglutire possono interferire con i pasti.", "Segnala ciò che accade e da quanto tempo. Se non riesci a bere o a trattenere liquidi, contatta tempestivamente il servizio che ti segue, seguendo le istruzioni ricevute per le urgenze."], questions: ["Quali difficoltà devo segnalare subito?", "Chi posso contattare tra una visita e l’altra?"], source: `${nci}/about-cancer/treatment/side-effects/nutrition` },
      { slug: "peso", title: "Il peso cambia: quando parlarne", description: "Riconoscere i cambiamenti senza giudizi sul proprio corpo.", paragraphs: ["Durante la malattia possono verificarsi perdita o aumento di peso. Appetito e alimentazione possono cambiare anche in relazione ai trattamenti.", "Non iniziare una dieta restrittiva per correggere da solo il cambiamento: riferiscilo al team e chiedi quali controlli e adattamenti siano appropriati per te."], questions: ["Come devo monitorare il peso?", "Questo cambiamento richiede un approfondimento?"], source: `${nci}/about-cancer/treatment/side-effects/appetite-loss` },
      { slug: "integratori", title: "Integratori e diete: prima chiedi", description: "Naturale non significa sempre compatibile con le cure.", paragraphs: ["Non ci sono prove che una dieta speciale o un integratore possano curare il cancro. Il supporto nutrizionale accompagna le terapie, non le sostituisce.", "Alcuni prodotti possono interferire con i trattamenti. Prima di iniziare integratori o regimi restrittivi, confrontati con il curante e comunica ciò che stai già assumendo."], questions: ["Questo prodotto è compatibile con la terapia?", "C’è una necessità documentata di integrazione?"], source: `${nci}/about-cancer/treatment/cam/diets-supplements` },
    ],
  },
  {
    slug: "attivita-fisica", title: "Attività fisica",
    description: "Muoversi non significa inseguire una prestazione. Durante e dopo le cure, il punto di partenza è un percorso adatto alla persona, concordato con i professionisti.", image: "/images/editorial/movimento.svg",
    articles: [
      { slug: "benefici", title: "Movimento e qualità della vita", description: "Che cosa può offrire un’attività adattata alla persona.", paragraphs: ["L’attività fisica adattata può contribuire a migliorare la funzione fisica e la qualità della vita durante e dopo i trattamenti. Non è una gara né una promessa sul risultato delle cure.", "Possibilità e limiti variano. Parla con il team prima di iniziare, soprattutto se sono presenti disturbi o limitazioni."], questions: ["Quali attività sono appropriate per me?", "Ho bisogno di supervisione?"], source: `${nci}/about-cancer/causes-prevention/risk/obesity/physical-activity-fact-sheet` },
      { slug: "percorso-personale", title: "Costruire un percorso personale", description: "Dal confronto con il curante alla scelta delle attività.", paragraphs: ["Un programma non può essere scelto soltanto in base al nome del tumore. Occorre considerare condizioni fisiche, trattamenti e capacità individuali.", "Porta alla visita le tue preferenze e le difficoltà concrete: camminare, salire le scale o riprendere un’attività abituale. Chiedi se serve una valutazione riabilitativa."], questions: ["Quali precauzioni devo seguire?", "Quando devo interrompere l’attività e contattarvi?"], source: `${nci}/about-cancer/causes-prevention/risk/obesity/physical-activity-fact-sheet` },
      { slug: "fatigue", title: "Quando la stanchezza non passa", description: "Capire la fatigue e chiedere una valutazione.", paragraphs: ["La fatigue legata al cancro può essere diversa dalla stanchezza abituale e non risolversi completamente con il riposo. Non è mancanza di volontà.", "Descrivi come interferisce con le tue giornate. Il team può valutarne le possibili cause e indicare un percorso: non forzarti a seguire programmi generici trovati online."], questions: ["Questa stanchezza richiede una valutazione?", "Come posso organizzare attività e pause?"], source: `${nci}/about-cancer/treatment/side-effects/fatigue` },
    ],
  },
  {
    slug: "sole-e-cura-della-pelle", title: "Sole e cura della pelle",
    description: "La pelle può avere esigenze diverse durante i trattamenti. Informarsi sulle precauzioni della propria terapia è il primo passo, anche quando le cure sono terminate.", image: "/images/editorial/pelle.svg",
    articles: [
      { slug: "durante-le-terapie", title: "Proteggere la pelle durante le terapie", description: "Che cosa verificare prima di esporsi al sole.", paragraphs: ["Alcuni trattamenti possono causare secchezza, irritazione o maggiore sensibilità della pelle al sole. Le indicazioni dipendono dalla terapia e dalla zona trattata.", "Chiedi quali protezioni e prodotti usare e segnala cambiamenti della pelle. Non applicare prodotti sulle aree trattate senza verificare le istruzioni del centro."], questions: ["La mia terapia aumenta la sensibilità al sole?", "Quali prodotti posso utilizzare?"], source: `${nci}/about-cancer/treatment/side-effects/skin-nail-changes` },
      { slug: "dopo-le-cure", title: "Dopo le cure: quali precauzioni mantenere?", description: "Il termine del trattamento non sostituisce una verifica individuale.", paragraphs: ["I tempi di recupero della pelle e le precauzioni possono variare. Non esiste un unico intervallo dopo il quale l’esposizione diventa appropriata per tutti.", "Durante il controllo chiedi quali indicazioni mantenere e quando rivalutarle. Segnala arrossamenti, lesioni o disturbi nuovi anziché trattarli autonomamente."], questions: ["Per quanto tempo devo mantenere queste precauzioni?", "Quali cambiamenti della pelle devo segnalare?"], source: `${nci}/about-cancer/treatment/side-effects/skin-nail-changes` },
    ],
  },
  {
    slug: "supporto-psicologico-e-psiconcologia", title: "Supporto psicologico e psiconcologia",
    description: "Non c’è un modo giusto di sentirsi davanti alla malattia. Dare spazio a emozioni, relazioni e bisogni significa prendersi cura della persona, oltre la diagnosi.", image: "/images/editorial/supporto.svg",
    articles: [
      { slug: "chiedere-supporto", title: "Chiedere supporto, senza dover essere forti", description: "Un primo orientamento verso l’aiuto psicologico.", paragraphs: ["Una diagnosi può portare emozioni diverse, che cambiano nel tempo. Non è necessario mostrarsi positivi in ogni momento né affrontare tutto da soli.", "Puoi chiedere al team se nel centro è disponibile un servizio di psiconcologia. Un professionista può aiutarti a dare spazio a paure e difficoltà, senza giudizio."], questions: ["Come posso accedere al supporto psicologico?", "È disponibile anche per i miei familiari?"], source: `${nci}/about-cancer/coping/feelings` },
      { slug: "caregiver", title: "Prendersi cura di chi accompagna", description: "Anche familiari e caregiver hanno bisogni da ascoltare.", paragraphs: ["Accompagnare una persona malata può assorbire tempo ed energie. Mettere sempre da parte i propri bisogni può rendere il percorso più difficile.", "Chiedere aiuto pratico e dividere i compiti non significa essere meno presenti. Informati presso il centro sui servizi e sui gruppi di supporto disponibili."], questions: ["Quali compiti possiamo distribuire?", "Esistono risorse dedicate ai caregiver?"], source: `${nci}/about-cancer/coping/caregiver-support` },
{"slug":"sessualita-e-intimita","title":"Sessualità e intimità: parlarne è possibile","description":"Riconoscere i cambiamenti e trovare uno spazio di confronto.","paragraphs":["Le cure possono influire sul desiderio, sul comfort e sull’immagine di sé. La sessualità è un tema legittimo da discutere con il team, anche se nessuno lo affronta per primo.","Puoi chiedere un colloquio riservato e coinvolgere il partner soltanto se lo desideri. Non ci sono tempi o aspettative da rispettare per dimostrare di stare meglio."],"questions":["A chi posso rivolgermi per i cambiamenti nella sfera sessuale?"],"source":"https://www.cancer.gov/about-cancer/coping/self-image"},
{"slug":"ritrovare-la-quotidianita","title":"Ritrovare la quotidianità dopo le cure","description":"Riprendere senza pretendere che tutto torni subito come prima.","paragraphs":["La fine dei trattamenti può accompagnarsi a sollievo ma anche a incertezza. Abitudini e priorità possono essere cambiate.","Concediti gradualità. Parla dei bisogni che restano durante i controlli e chiedi supporto per costruire una routine compatibile con le tue energie."],"questions":["Quali risorse possono aiutarmi nella fase successiva alle cure?"],"source":"https://www.cancer.gov/about-cancer/coping/survivorship/new-normal"},
{"slug":"parole-per-raccontare-la-malattia","title":"Le parole per raccontare la malattia","description":"Scegliere un linguaggio che rispetti la propria esperienza.","paragraphs":["Non tutti si riconoscono nelle parole «battaglia», «vittoria» o «sconfitta». Puoi scegliere come descrivere ciò che vivi.","A chi ti sta vicino puoi dire quali espressioni ti aiutano e quali ti pesano. Non devi sentirti obbligato a raccontare la malattia come un’esperienza positiva."],"questions":["Come posso esprimere ciò che preferisco non sentirmi dire?"],"source":"https://www.cancer.gov/about-cancer/coping/feelings"},
{"slug":"paura-e-incertezza","title":"Affrontare la paura e l’incertezza","description":"Dare spazio anche alle domande più difficili.","paragraphs":["Le preoccupazioni per il futuro possono essere intense. Parlarne non significa rinunciare alla speranza.","Se i pensieri diventano difficili da gestire, chiedi uno spazio di ascolto professionale. Le domande sulla prognosi vanno affrontate con il medico, nella tua situazione specifica."],"questions":["Possiamo dedicare un colloquio alle mie preoccupazioni?"],"source":"https://www.cancer.gov/about-cancer/coping/feelings/anxiety-distress-pdq"},
{"slug":"parlarne-con-i-figli","title":"Come parlarne con i figli","description":"Preparare il dialogo, tenendo conto della loro età.","paragraphs":["Affrontare la diagnosi in famiglia può sollevare dubbi su cosa dire e come rispondere. Non serve avere subito tutte le parole.","Chiedi al servizio di supporto psicologico aiuto per preparare una comunicazione adatta all’età e alle domande dei figli, senza promettere ciò che non puoi sapere."],"questions":["Potete aiutarmi a preparare il dialogo con i miei figli?"],"source":"https://www.cancer.gov/about-cancer/coping/adjusting-to-cancer"},
{"slug":"dialogo-con-il-team","title":"Costruire il dialogo con il team curante","description":"Domande, chiarimenti e decisioni condivise.","paragraphs":["Puoi chiedere spiegazioni comprensibili, prendere appunti e segnalare ciò che non è chiaro. Portare una lista di domande aiuta a dare spazio alle tue priorità.","Se lo desideri, chiedi a una persona di fiducia di accompagnarti. Esprimi quanto vuoi sapere e quali aspetti ti preoccupano."],"questions":["Quali informazioni servono per capire il prossimo passo?"],"source":"https://www.cancer.gov/about-cancer/coping/adjusting-to-cancer"},
{"slug":"amici-e-familiari","title":"Parlarne con amici e familiari","description":"Decidere cosa condividere e quale aiuto chiedere.","paragraphs":["Puoi scegliere con chi condividere la diagnosi e quanto raccontare. Non devi aggiornare tutti nello stesso modo.","Se ti è utile, concorda un aiuto concreto: accompagnamento, pasti, commissioni o semplicemente compagnia. Puoi anche chiedere tranquillità e riservatezza."],"questions":["Quale aiuto concreto mi farebbe comodo questa settimana?"],"source":"https://www.cancer.gov/about-cancer/coping/adjusting-to-cancer/spouse-or-partner"},
{"slug":"affrontare-la-diagnosi","title":"I primi giorni dopo la diagnosi","description":"Trovare riferimenti senza dover risolvere tutto subito.","paragraphs":["Ricevere una diagnosi può rendere difficile assimilare molte informazioni insieme. Le reazioni possono essere diverse e cambiare nel tempo.","Annota le domande che emergono e chiedi a chi rivolgerti per chiarimenti. Per il disagio emotivo, puoi domandare un contatto con il servizio di supporto psicologico."],"questions":["Chi posso contattare se dopo la visita emergono altri dubbi?"],"source":"https://www.cancer.gov/about-cancer/coping/feelings/anxiety-distress-pdq"},
{"slug":"malattia-e-lavoro","title":"Malattia e lavoro: preparare il confronto","description":"Bisogni pratici e comunicazione, senza esporsi più del necessario.","paragraphs":["Rientrare o continuare a lavorare può richiedere un confronto sui bisogni e sulle energie disponibili. Non tutte le situazioni sono uguali.","Prepara le questioni che vuoi discutere con il curante. Per diritti, certificazioni e obblighi italiani rivolgiti a servizi competenti: questa pagina non fornisce indicazioni legali."],"questions":["Quali aspetti del lavoro devo discutere con il medico?"],"source":"https://www.cancer.gov/about-cancer/coping/day-to-day/back-to-work"},
{"slug":"chirurgia-e-vissuto-emotivo","title":"Chirurgia e vissuto emotivo","description":"Prepararsi anche a ciò che un intervento può significare per sé.","paragraphs":["Un intervento può suscitare domande sul corpo e sulla vita quotidiana. Sono temi da portare al colloquio insieme agli aspetti clinici.","Chiedi quali cambiamenti aspettarti e quali risorse di supporto siano disponibili. Non devi minimizzare una preoccupazione perché sembra meno importante delle altre."],"questions":["Possiamo parlare anche delle mie preoccupazioni per i cambiamenti del corpo?"],"source":"https://www.cancer.gov/about-cancer/coping/self-image"},
{"slug":"corpo-e-immagine-di-se","title":"Il corpo cambia, la persona resta","description":"Accogliere il proprio vissuto senza imporre tempi.","paragraphs":["Cicatrici e altri cambiamenti legati alla malattia o alle cure possono influire sul modo di percepirsi. Ogni persona li vive diversamente.","Puoi chiedere sostegno e informazioni sui percorsi disponibili. Non sei tenuto a mostrare il corpo o a sentirti a tuo agio prima di essere pronto."],"questions":["Quale supporto posso chiedere per il rapporto con il mio corpo?"],"source":"https://www.cancer.gov/about-cancer/coping/self-image"},
      { slug: "emozioni", title: "Dare un nome alle emozioni", description: "Trovare le parole, rispettando i propri tempi.", paragraphs: ["Paura, tristezza o rabbia possono emergere in momenti diversi. Le reazioni non sono uguali per tutte le persone e non definiscono il loro valore.", "Se il disagio pesa sulla vita quotidiana, raccontalo al team. Puoi scegliere con chi parlare e chiedere uno spazio professionale di ascolto."], questions: ["Con chi posso parlare di ciò che provo?", "Come posso spiegare ai miei familiari ciò di cui ho bisogno?"], source: `${nci}/about-cancer/coping/feelings` },
    ],
  },
];
